# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /work

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /work

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	cd /work && /usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	cd /work && /usr/bin/cpack --config ./CPackSourceConfig.cmake /work/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"canpi\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /work && $(CMAKE_COMMAND) -E cmake_progress_start /work/CMakeFiles /work/canpi//CMakeFiles/progress.marks
	cd /work && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 canpi/all
	$(CMAKE_COMMAND) -E cmake_progress_start /work/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /work && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 canpi/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /work && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 canpi/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /work && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 canpi/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /work && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
canpi/CMakeFiles/canpi.dir/rule:
	cd /work && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 canpi/CMakeFiles/canpi.dir/rule
.PHONY : canpi/CMakeFiles/canpi.dir/rule

# Convenience name for target.
canpi: canpi/CMakeFiles/canpi.dir/rule
.PHONY : canpi

# fast build rule for target.
canpi/fast:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/build
.PHONY : canpi/fast

src/Client.o: src/Client.cpp.o
.PHONY : src/Client.o

# target to build an object file
src/Client.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/Client.cpp.o
.PHONY : src/Client.cpp.o

src/Client.i: src/Client.cpp.i
.PHONY : src/Client.i

# target to preprocess a source file
src/Client.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/Client.cpp.i
.PHONY : src/Client.cpp.i

src/Client.s: src/Client.cpp.s
.PHONY : src/Client.s

# target to generate assembly for a file
src/Client.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/Client.cpp.s
.PHONY : src/Client.cpp.s

src/Turnout.o: src/Turnout.cpp.o
.PHONY : src/Turnout.o

# target to build an object file
src/Turnout.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/Turnout.cpp.o
.PHONY : src/Turnout.cpp.o

src/Turnout.i: src/Turnout.cpp.i
.PHONY : src/Turnout.i

# target to preprocess a source file
src/Turnout.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/Turnout.cpp.i
.PHONY : src/Turnout.cpp.i

src/Turnout.s: src/Turnout.cpp.s
.PHONY : src/Turnout.s

# target to generate assembly for a file
src/Turnout.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/Turnout.cpp.s
.PHONY : src/Turnout.cpp.s

src/canHandler.o: src/canHandler.cpp.o
.PHONY : src/canHandler.o

# target to build an object file
src/canHandler.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/canHandler.cpp.o
.PHONY : src/canHandler.cpp.o

src/canHandler.i: src/canHandler.cpp.i
.PHONY : src/canHandler.i

# target to preprocess a source file
src/canHandler.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/canHandler.cpp.i
.PHONY : src/canHandler.cpp.i

src/canHandler.s: src/canHandler.cpp.s
.PHONY : src/canHandler.s

# target to generate assembly for a file
src/canHandler.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/canHandler.cpp.s
.PHONY : src/canHandler.cpp.s

src/edSession.o: src/edSession.cpp.o
.PHONY : src/edSession.o

# target to build an object file
src/edSession.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/edSession.cpp.o
.PHONY : src/edSession.cpp.o

src/edSession.i: src/edSession.cpp.i
.PHONY : src/edSession.i

# target to preprocess a source file
src/edSession.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/edSession.cpp.i
.PHONY : src/edSession.cpp.i

src/edSession.s: src/edSession.cpp.s
.PHONY : src/edSession.s

# target to generate assembly for a file
src/edSession.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/edSession.cpp.s
.PHONY : src/edSession.cpp.s

src/frameCAN.o: src/frameCAN.cpp.o
.PHONY : src/frameCAN.o

# target to build an object file
src/frameCAN.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/frameCAN.cpp.o
.PHONY : src/frameCAN.cpp.o

src/frameCAN.i: src/frameCAN.cpp.i
.PHONY : src/frameCAN.i

# target to preprocess a source file
src/frameCAN.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/frameCAN.cpp.i
.PHONY : src/frameCAN.cpp.i

src/frameCAN.s: src/frameCAN.cpp.s
.PHONY : src/frameCAN.s

# target to generate assembly for a file
src/frameCAN.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/frameCAN.cpp.s
.PHONY : src/frameCAN.cpp.s

src/gpio.o: src/gpio.cpp.o
.PHONY : src/gpio.o

# target to build an object file
src/gpio.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/gpio.cpp.o
.PHONY : src/gpio.cpp.o

src/gpio.i: src/gpio.cpp.i
.PHONY : src/gpio.i

# target to preprocess a source file
src/gpio.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/gpio.cpp.i
.PHONY : src/gpio.cpp.i

src/gpio.s: src/gpio.cpp.s
.PHONY : src/gpio.s

# target to generate assembly for a file
src/gpio.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/gpio.cpp.s
.PHONY : src/gpio.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/nodeConfigurator.o: src/nodeConfigurator.cpp.o
.PHONY : src/nodeConfigurator.o

# target to build an object file
src/nodeConfigurator.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/nodeConfigurator.cpp.o
.PHONY : src/nodeConfigurator.cpp.o

src/nodeConfigurator.i: src/nodeConfigurator.cpp.i
.PHONY : src/nodeConfigurator.i

# target to preprocess a source file
src/nodeConfigurator.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/nodeConfigurator.cpp.i
.PHONY : src/nodeConfigurator.cpp.i

src/nodeConfigurator.s: src/nodeConfigurator.cpp.s
.PHONY : src/nodeConfigurator.s

# target to generate assembly for a file
src/nodeConfigurator.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/nodeConfigurator.cpp.s
.PHONY : src/nodeConfigurator.cpp.s

src/opc_codes.o: src/opc_codes.cpp.o
.PHONY : src/opc_codes.o

# target to build an object file
src/opc_codes.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/opc_codes.cpp.o
.PHONY : src/opc_codes.cpp.o

src/opc_codes.i: src/opc_codes.cpp.i
.PHONY : src/opc_codes.i

# target to preprocess a source file
src/opc_codes.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/opc_codes.cpp.i
.PHONY : src/opc_codes.cpp.i

src/opc_codes.s: src/opc_codes.cpp.s
.PHONY : src/opc_codes.s

# target to generate assembly for a file
src/opc_codes.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/opc_codes.cpp.s
.PHONY : src/opc_codes.cpp.s

src/sessionHandler.o: src/sessionHandler.cpp.o
.PHONY : src/sessionHandler.o

# target to build an object file
src/sessionHandler.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/sessionHandler.cpp.o
.PHONY : src/sessionHandler.cpp.o

src/sessionHandler.i: src/sessionHandler.cpp.i
.PHONY : src/sessionHandler.i

# target to preprocess a source file
src/sessionHandler.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/sessionHandler.cpp.i
.PHONY : src/sessionHandler.cpp.i

src/sessionHandler.s: src/sessionHandler.cpp.s
.PHONY : src/sessionHandler.s

# target to generate assembly for a file
src/sessionHandler.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/sessionHandler.cpp.s
.PHONY : src/sessionHandler.cpp.s

src/tcpClient.o: src/tcpClient.cpp.o
.PHONY : src/tcpClient.o

# target to build an object file
src/tcpClient.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/tcpClient.cpp.o
.PHONY : src/tcpClient.cpp.o

src/tcpClient.i: src/tcpClient.cpp.i
.PHONY : src/tcpClient.i

# target to preprocess a source file
src/tcpClient.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/tcpClient.cpp.i
.PHONY : src/tcpClient.cpp.i

src/tcpClient.s: src/tcpClient.cpp.s
.PHONY : src/tcpClient.s

# target to generate assembly for a file
src/tcpClient.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/tcpClient.cpp.s
.PHONY : src/tcpClient.cpp.s

src/tcpClientGridConnect.o: src/tcpClientGridConnect.cpp.o
.PHONY : src/tcpClientGridConnect.o

# target to build an object file
src/tcpClientGridConnect.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/tcpClientGridConnect.cpp.o
.PHONY : src/tcpClientGridConnect.cpp.o

src/tcpClientGridConnect.i: src/tcpClientGridConnect.cpp.i
.PHONY : src/tcpClientGridConnect.i

# target to preprocess a source file
src/tcpClientGridConnect.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/tcpClientGridConnect.cpp.i
.PHONY : src/tcpClientGridConnect.cpp.i

src/tcpClientGridConnect.s: src/tcpClientGridConnect.cpp.s
.PHONY : src/tcpClientGridConnect.s

# target to generate assembly for a file
src/tcpClientGridConnect.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/tcpClientGridConnect.cpp.s
.PHONY : src/tcpClientGridConnect.cpp.s

src/tcpServer.o: src/tcpServer.cpp.o
.PHONY : src/tcpServer.o

# target to build an object file
src/tcpServer.cpp.o:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/tcpServer.cpp.o
.PHONY : src/tcpServer.cpp.o

src/tcpServer.i: src/tcpServer.cpp.i
.PHONY : src/tcpServer.i

# target to preprocess a source file
src/tcpServer.cpp.i:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/tcpServer.cpp.i
.PHONY : src/tcpServer.cpp.i

src/tcpServer.s: src/tcpServer.cpp.s
.PHONY : src/tcpServer.s

# target to generate assembly for a file
src/tcpServer.cpp.s:
	cd /work && $(MAKE) $(MAKESILENT) -f canpi/CMakeFiles/canpi.dir/build.make canpi/CMakeFiles/canpi.dir/src/tcpServer.cpp.s
.PHONY : src/tcpServer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... canpi"
	@echo "... src/Client.o"
	@echo "... src/Client.i"
	@echo "... src/Client.s"
	@echo "... src/Turnout.o"
	@echo "... src/Turnout.i"
	@echo "... src/Turnout.s"
	@echo "... src/canHandler.o"
	@echo "... src/canHandler.i"
	@echo "... src/canHandler.s"
	@echo "... src/edSession.o"
	@echo "... src/edSession.i"
	@echo "... src/edSession.s"
	@echo "... src/frameCAN.o"
	@echo "... src/frameCAN.i"
	@echo "... src/frameCAN.s"
	@echo "... src/gpio.o"
	@echo "... src/gpio.i"
	@echo "... src/gpio.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/nodeConfigurator.o"
	@echo "... src/nodeConfigurator.i"
	@echo "... src/nodeConfigurator.s"
	@echo "... src/opc_codes.o"
	@echo "... src/opc_codes.i"
	@echo "... src/opc_codes.s"
	@echo "... src/sessionHandler.o"
	@echo "... src/sessionHandler.i"
	@echo "... src/sessionHandler.s"
	@echo "... src/tcpClient.o"
	@echo "... src/tcpClient.i"
	@echo "... src/tcpClient.s"
	@echo "... src/tcpClientGridConnect.o"
	@echo "... src/tcpClientGridConnect.i"
	@echo "... src/tcpClientGridConnect.s"
	@echo "... src/tcpServer.o"
	@echo "... src/tcpServer.i"
	@echo "... src/tcpServer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /work && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

